### ISSUE TITLE
restrict no-extra-parens to functions only

### ISSUE THREAD

**Issue by andrewdeandrade** [uber/standard#31]
When this rule was originally proposed, @raynos suggested that it might lead to reduced readability, but lets give it a shot. It appears that @ardok  might have a reasonable example of code that should be allowed so maybe this rule should be relaxed to only applying to functions, `e.g. [2, "functions"]` in the rc file.

https://github.com/eslint/eslint/blob/master/docs/rules/no-extra-parens.md

**Comment by ardok** [comment]
```
// `response` is a response object that we get from server

// This should be allowed since it shows the developer's intention clearly
var numPage = (response && response.page) || 1;

// Just by a quick glance, the example below is definitely more "confusing" than the one above
var numPage = response && response.page || 1;
```

**Comment by Raynos** [comment]
:+1: for "functions" only.

**Comment by rtsao** [comment]
I agree, I think redundant parens can be useful for readability such as @ardok's example.

**Comment by andrewdeandrade** [comment]
Feel free to submit a PR to restrict no-extra-parens to functions only in es6 mode.

**Comment by rtsao** [comment]
Why only ES6 and not standard mode also?

**Comment by Raynos** [comment]
lets do it in standard mode too.
